[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "openpyxl",
    "fhir.resources>=6.4",
    "pydantic",
    "validators",
    "odfpy",
    "ocldev",
    "requests-toolbelt",
]
build-backend = "setuptools.build_meta"